version: '3.8'
services:
  web:
    image: nginx
    container_name: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "81:80"
    environment:
    - NGINX_HOST=myorganize.com
    - NGINX_PORT=80